# Generated by Django 5.2 on 2025-05-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_answer_user_pollresponse_answer_poll_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollresponse',
            name='respondent_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='pollresponse',
            name='respondent_surname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
    ]
